---
driver:
  name: vagrant
  customize:
    memory: 4192
 
provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

# network is only necessary if accessing SmartSense via UI
platforms:
  - name: ubuntu-14.04
    run_list:
       - 'recipe[apt::default]'
       - 'recipe[java::oracle]'
       - 'recipe[smartsense-chef::default]'
    attributes: {
      java: {
        oracle: {
          accept_oracle_download_terms: true,
          jce: { 
            enabled: true 
          }
        },
        jdk_version: 8,
        install_flavor: oracle,
        accept_license_agreement: true,
        set_default: true
      }
    }
    driver:
      box: bento/ubuntu-14.04
      network:
      - [ "private_network" , { ip : "192.168.33.7" } ]	

suites:
  - name: default
    attributes:
