name 'smartsense-chef'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures smartsense-chef'
long_description 'Installs/Configures smartsense-chef'
version '0.1.0'
